//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Adar.rc
//
#define ID_KEY_Q                        101
#define ID_Q_CTL_S                      102
#define IDI_ICON1                       103
#define IDI_ICON3                       103
#define IDI_ICON2                       104
#define IDR_MENU1                       109
#define IDI_ICON_REC                    110
#define IDR_MENU2                       110
#define IDI_ICON_PLAY                   111
#define BK1                             153
#define IDR_ACCELERATOR1                154
#define IDB_COLON                       155
#define IDB_DIGIT0                      156
#define IDB_DIGIT1                      157
#define IDB_DIGIT2                      158
#define IDB_DIGIT3                      159
#define IDB_DIGIT4                      160
#define IDB_DIGIT5                      161
#define IDB_DIGIT6                      162
#define IDB_DIGIT7                      163
#define IDB_DIGIT8                      164
#define IDB_DIGIT9                      165
#define IDD_DIALOG1                     167
#define IDD_DIALOG_MAIN                 167
#define IDD_DIALOG2                     168
#define IDD_DIALOG_INDEX                168
#define IDD_DIALOG_ABOUT                169
#define IDD_DIALOG3                     171
#define IDB_BITMAP_ABOUT                176
#define IDI_ICON4                       178
#define IDI_ICON                        179
#define IDI_ICON6                       180
#define IDD_DIALOG_AFM                  183
#define IDD_DIALOG_SETTIME              184
#define IDD_DIALOG_OPTIONS_NEW          186
#define IDB_BITMAP_ABOUT2               201
#define IDB_BITMAP_FILEBUTTON           209
#define IDB_BITMAP_RECORDBUTTON         211
#define IDB_BITMAP_STOPBUTTON           212
#define IDB_BITMAP_CLOSEBUTTON          213
#define IDB_BITMAP_EXITBUTTON           214
#define IDB_BITMAP_PANEL                217
#define IDD_DIALOG_FILESETTINGS         218
#define IDD_DIALOG_MAIN_SMALL           219
#define IDD_DIALOG_OPTIONS              220
#define IDD_DIALOG_ENTERREG             221
#define IDC_RECORD                      1000
#define IDC_STOP                        1007
#define IDC_WAVE                        1008
#define IDC_PLAY                        1009
#define IDC_RECORD_LIGHT                1014
#define IDC_CLOCK                       1018
#define IDC_SQUELCH_LIGHT               1019
#define IDC_CLOCK2                      1020
#define IDC_TOD1                        1022
#define IDC_LIST1                       1024
#define IDC_STATIC_TEXT1                1025
#define IDC_REFRESH                     1026
#define IDC_SLIDER_SQUELCH              1029
#define IDC_STATIC_SQ_VAL               1030
#define IDC_STATIC_ABOUT_VERSION        1032
#define IDC_CHECK_AUTOSCROLL            1033
#define IDC_COMBO_SMP_RATE              1038
#define IDC_BUTTON_ABOUT_WEB            1040
#define IDC_STATIC_ABOUT_FRAME          1042
#define IDC_EDIT_FREE                   1043
#define IDC_EDIT3                       1048
#define IDC_RADIO_AUTORECORD_NAME_TYPE  1049
#define IDC_CHECK_AUTO_RECORD           1050
#define IDC_RADIO_AUTORECORD_NAME_TYPE2 1051
#define IDC_BUTTON1                     1052
#define IDC_BUTTON_REGISTER             1052
#define IDC_BUTTON_RESISTER             1052
#define IDC_EDIT_AUTOSTOP_DURATION      1055
#define IDC_EDIT_AUTOSTOP_SIZE          1058
#define IDC_EDIT_AUTOSTOP_AT            1060
#define IDC_BUTTON2                     1062
#define IDC_CHECK_AUTOSTOP_SIZE         1063
#define IDC_CHECK_AUTOSTOP_MANUAL       1064
#define IDC_CHECK_AUTOSTOP_TIMELIM      1065
#define IDC_CHECK_AUTOSTOP_TIME         1066
#define IDC_EDIT_TIME_HH                1066
#define IDC_EDIT_TIME_MM                1067
#define IDC_EDIT_TIME_SS                1068
#define IDC_SPIN_TIME_HH                1069
#define IDC_SPIN_TIME_MM                1070
#define IDC_SPIN_TIME_SS                1071
#define IDC_CHECK_USE_COMPRESSION       1073
#define IDC_RADIO_MONO                  1075
#define IDC_RADIO_STEREO                1076
#define IDC_RADIO_8BIT                  1077
#define IDC_RADIO_16BIT                 1078
#define IDC_EDIT_OFFSETMEAS             1080
#define IDC_EDIT_OFFSETMEAS2            1081
#define IDC_EDIT_OFFSETMEAS3            1082
#define IDC_EDIT_OFFSETMEAS4            1083
#define IDC_SPIN_SEQDIGITS              1085
#define IDC_BUTTON_FILESETTINGSDLG      1086
#define IDC_STATIC_SEQDIGITS            1087
#define IDC_RADIO_FILEMANUAL            1088
#define IDC_RADIO_FILEAPPENDSEQ         1089
#define IDC_RADIO_FILEAPPENDDATE        1090
#define IDC_EDIT1                       1091
#define IDC_EDIT_NAME                   1091
#define IDC_EDIT2                       1092
#define IDC_EDIT_KEY                    1092
#define IDC_OPTIONS_EDIT_SQDLY          1093
#define IDC_STATIC_FREE                 1096
#define IDC_CHECK1                      1097
#define IDC_STATIC_OFFSETMEAS           1097
#define IDC_CHECK_ENABLEANTICLIP        1097
#define IDC_SPIN_FREQ                   1098
#define IDC_STATIC_OFFSETMEAS2          1098
#define IDC_SPIN_DURATION               1099
#define IDC_SPIN_VOL                    1100
#define IDC_EDIT_FREQ                   1101
#define IDC_EDIT_DURATION               1102
#define IDC_EDIT_VOL                    1103
#define IDC_CHECK2                      1104
#define IDC_CHECK_ENABLEPIP             1104
#define IDC_STATIC_REGNAME              1105
#define IDC_STATIC_REGCODE              1106
#define IDC_STATIC_VERSION              1107
#define IDC_RADIO_CAL_OFF               1125
#define IDC_RADIO_CAL_TRACK             1127
#define IDC_RADIO_CAL_LOCK              1128
#define ID_FILE_EXIT                    40003
#define ID_HELP_ABOUT                   40004
#define ID_DEVICE_OPENWAVE              40005
#define ID_DEVICE_CLOSEWAVE             40006
#define ID_FILE_SAVEAS                  40012
#define ID_OPTIONS_DISPLAYINDEX         40017
#define ID_OPTIONS                      40028
#define ID_TEST_GETTIME                 40030
#define ID_KEY_CTL_S                    40031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        222
#define _APS_NEXT_COMMAND_VALUE         40033
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
